services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_LOG_LEVEL=DEBUG
    depends_on:
      jaeger:
        condition: service_healthy

  app-healthcheck:
    image: curlimages/curl:latest@sha256:7c12af72ceb38b7432ab85e1a265cff6ae58e06f95539d539b654f2cfa64bb13
    command: ["sleep", "infinity"]
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:3000/"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  jaeger:
    image: jaegertracing/jaeger:latest@sha256:46a886260e04002d8f45e213fc39063fa11a50446048fdaa64786fc0840cb9f8
    ports:
      - "16686:16686"  # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133/status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
