services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_LOG_LEVEL=DEBUG
    depends_on:
      jaeger:
        condition: service_healthy

  app-healthcheck:
    image: curlimages/curl:latest
    command: ["sleep", "infinity"]
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:3000/"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"  # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133/status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
