name: PR Auto-merge

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        
      - name: Run tests
        uses: takumi3488/mygha/bun/test@cb3df2bec9fd7f18e2ebbf13c43714f92bb33162 # main
        with:
          skip-test: true

