name: PR Auto-merge

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        
      - name: Run tests
        uses: takumi3488/mygha/bun/test@0c1c6db7145ad078080246e0b7177f9cc364fb2d # main
        with:
          skip-test: true

