name: PR Auto-merge

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        
      - name: Run tests
        uses: takumi3488/mygha/bun/test@3ca84db7e69099e8d68bcdd5d2a5843f5a5f1fd3 # main
        with:
          skip-test: true

